tracker-parameters:
  AlphaRatio:
    pid: 01qwqwdlc922_sample_pid_d93fqd6fji9
  BroadcastTheNet:
    pid: 01qwqwdlc922_sample_pid_d93fqd6fji9
  PassThePopcorn:
    pid: 01qwqwdlc922_sample_pid_d93fqd6fji9
  TorrentLeech:
    pid: 01qwqwdlc922_sample_pid_d93fqd6fji9
  UHDBits:
    pid: 01qwqwdlc922_sample_pid_d93fqd6fji9